sonar.projectKey=protein-pro-app
sonar.projectName=Protein Pro App
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
sonar.coverage.jacoco.xmlReportPaths=api-gateway/target/site/jacoco/jacoco.xml,authentication-service/target/site/jacoco/jacoco.xml,user-profile-service/target/site/jacoco/jacoco.xml,protein-service/target/site/jacoco/jacoco.xml,bookmark-service/target/site/jacoco/jacoco.xml
